=== mpwcode/netrunner/schema/v2/cards_schema.json
{
  "$id": "https://github.com/netrunnerdb/netrunner-cards-json/blob/master/schema/v2/cards_schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "allOf": [
    {
      "title": "Faction id must be valid for the side.",
      "type": "object",
      "oneOf": [
        {
          "properties": {
            "side_id": {
              "const": "corp"
            },
            "faction_id": {
              "enum": [
                "haas_bioroid",
                "jinteki",
                "nbn",
                "neutral_corp",
                "weyland_consortium"
              ]
            }
          }
        },
        {
          "properties": {
            "side_id": {
              "const": "runner"
            },
            "faction_id": {
              "enum": [
                "adam",
                "anarch",
                "apex",
                "criminal",
                "neutral_runner",
                "shaper",
                "sunny_lebeau"
              ]
            }
          }
        }
      ]
    },
    {
      "title": "Type ids must be valid for the side.",
      "type": "object",
      "oneOf": [
        {
          "properties": {
            "side_id": {
              "const": "corp"
            },
            "card_type_id": {
              "enum": [
                "agenda",
                "asset",
                "corp_identity",
                "ice",
                "operation",
                "upgrade"
              ]
            }
          }
        },
        {
          "properties": {
            "side_id": {
              "const": "runner"
            },
            "card_type_id": {
              "enum": [
                "event",
                "hardware",
                "program",
                "resource",
                "runner_identity"
              ]
            }
          }
        }
      ]
    }
  ],
  "oneOf": [
    {
      "properties": {
        "advancement_requirement": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "agenda_points": {
          "minimum": 0,
          "type": "integer"
        },
        "card_type_id": {
          "const": "agenda"
        }
      },
      "required": ["advancement_requirement", "agenda_points"]
    },
    {
      "properties": {
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "trash_cost": {
          "minimum": 0,
          "type": "integer"
        },
        "card_type_id": {
          "enum": ["asset", "upgrade"]
        }
      },
      "required": ["cost", "trash_cost"]
    },
    {
      "properties": {
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "strength": {
          "oneOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "card_type_id": {
          "enum": ["ice"]
        }
      },
      "required": ["cost", "strength"]
    },
    {
      "properties": {
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "card_type_id": {
          "enum": ["event", "hardware", "operation", "program", "resource"]
        }
      },
      "required": ["cost"]
    },
    {
      "properties": {
        "influence_limit": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "minimum_deck_size": {
          "minimum": 0,
          "type": "integer"
        },
        "card_type_id": {
          "enum": ["corp_identity", "runner_identity"]
        }
      },
      "required": ["influence_limit", "minimum_deck_size"]
    }
  ],
  "properties": {
    "advancement_requirement": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "agenda_points": {
      "minimum": 0,
      "type": "integer"
    },
    "attribution": {
      "minLength": 1,
      "type": "string"
    },
    "base_link": {
      "minimum": 0,
      "type": "integer"
    },
    "id": {
      "minLength": 1,
      "type": "string"
    },
    "cost": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "deck_limit": {
      "minimum": 1,
      "type": "integer"
    },
    "faction_id": {
      "minLength": 1,
      "type": "string"
    },
    "influence_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "influence_limit": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "layout_id": {
      "oneOf": [
        {
          "type": "string",
          "enum": ["normal", "flip", "copy", "facade", "progression"]
        },
        {
          "type": "null"
        }
      ]
    },
    "memory_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "minimum_deck_size": {
      "minimum": 0,
      "type": "integer"
    },
    "side_id": {
      "minLength": 1,
      "type": "string",
      "enum": ["corp", "runner"]
    },
    "faces": {
      "oneOf": [
        {
          "type": "array"
        },
        {
          "type": "null"
        }
      ]
    },
    "strength": {
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "stripped_text": {
      "minLength": 1,
      "type": "string"
    },
    "stripped_title": {
      "minLength": 1,
      "type": "string"
    },
    "text": {
      "minLength": 1,
      "type": "string"
    },
    "title": {
      "minLength": 1,
      "type": "string"
    },
    "trash_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "card_type_id": {
      "minLength": 1,
      "type": "string"
    },
    "is_unique": {
      "type": "boolean"
    },
    "subtypes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "id",
    "faction_id",
    "deck_limit",
    "side_id",
    "title",
    "card_type_id",
    "is_unique"
  ],
  "dependentSchemas": {
    "layout_id": {
      "oneOf": [
        {
          "properties": {
            "layout_id": {
              "oneOf": [
                {
                  "const": "normal"
                },
                {
                  "type": "null"
                }
              ]
            },
            "faces": {
              "type": "null"
            }
          }
        },
        {
          "properties": {
            "layout_id": {
              "const": "flip"
            },
            "faces": {
              "type": "array",
              "minItems": 1,
              "maxItems": 1,
              "items": {
                "type": "object"
              }
            }
          },
          "required": ["faces"]
        },
        {
          "properties": {
            "layout_id": {
              "const": "copy"
            },
            "faces": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "object"
              }
            }
          },
          "required": ["faces"]
        },
        {
          "properties": {
            "layout_id": {
              "const": "facade"
            },
            "faces": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "object"
              }
            }
          },
          "required": ["faces"]
        },
        {
          "properties": {
            "layout_id": {
              "const": "progression"
            },
            "faces": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "object"
              }
            }
          },
          "required": ["faces"]
        }
      ]
    }
  }
}

=== mpwcode/netrunner/v2/cards/laser_pointer.json
{
  "id": "laser_pointer",
  "card_type_id": "program",
  "cost": 2,
  "deck_limit": 3,
  "faction_id": "criminal",
  "influence_cost": 3,
  "is_unique": false,
  "memory_cost": 1,
  "side_id": "runner",
  "stripped_text": "Whenever you encounter a piece of AP, destroyer, or observer ice, you may trash this program to bypass that ice.",
  "stripped_title": "Laser Pointer",
  "subtypes": ["weapon"],
  "text": "Whenever you encounter a piece of <strong>AP</strong>, <strong>destroyer</strong>, or <strong>observer</strong> ice, you may trash this program to bypass that ice.",
  "title": "Laser Pointer"
}

=== mpwcode/netrunner/v2/cards/greasing_the_palm.json
{
  "id": "greasing_the_palm",
  "card_type_id": "operation",
  "cost": 3,
  "deck_limit": 3,
  "faction_id": "haas_bioroid",
  "influence_cost": 3,
  "is_unique": false,
  "side_id": "corp",
  "stripped_text": "Gain 5 credits. You may install 1 card from HQ. You may remove 1 tag to place 1 advancement counter on that card.",
  "stripped_title": "Greasing the Palm",
  "subtypes": ["transaction"],
  "text": "Gain 5[credit]. You may install 1 card from HQ. You may remove 1 tag to place 1 advancement counter on that card.",
  "title": "Greasing the Palm"
}

=== mpwcode/netrunner/v2/cards/joy_ride.json
{
  "attribution": "Designed by 2020 American Continental Champion Jason Ford",
  "id": "joy_ride",
  "card_type_id": "event",
  "cost": 2,
  "deck_limit": 3,
  "faction_id": "shaper",
  "influence_cost": 3,
  "is_unique": false,
  "side_id": "runner",
  "stripped_text": "Run R&D. If successful, draw 5 cards.",
  "stripped_title": "Joy Ride",
  "subtypes": ["run"],
  "text": "Run R&D. If successful, draw 5 cards.",
  "title": "Joy Ride"
}

=== mpwcode/netrunner/v2/cards/vaporframe_fabricator.json
{
  "card_type_id": "asset",
  "cost": 2,
  "deck_limit": 3,
  "faction_id": "haas_bioroid",
  "id": "vaporframe_fabricator",
  "influence_cost": 3,
  "is_unique": false,
  "side_id": "corp",
  "stripped_text": "click: Install 1 card from HQ, ignoring all costs. Use this ability only once per turn. When the Runner trashes this asset, you may install 1 card from HQ, ignoring all costs. You cannot install that card in the root of this server.",
  "stripped_title": "Vaporframe Fabricator",
  "text": "<strong>[click]:</strong> Install 1 card from HQ, ignoring all costs. Use this ability only once per turn.\nWhen the Runner trashes this asset, you may install 1 card from HQ, ignoring all costs. You cannot install that card in the root of this server.",
  "title": "Vaporframe Fabricator",
  "trash_cost": 3
}

=== mpwcode/netrunner/v2/cards/lago_paranoa_shelter.json
{
  "id": "lago_paranoa_shelter",
  "card_type_id": "resource",
  "cost": 2,
  "deck_limit": 3,
  "faction_id": "anarch",
  "influence_cost": 2,
  "is_unique": true,
  "side_id": "runner",
  "stripped_text": "The first time each turn the Corp installs a card in the root of a server, you may trash the top card of your stack to draw 1 card.",
  "stripped_title": "Lago Paranoa Shelter",
  "subtypes": ["connection", "location"],
  "text": "The first time each turn the Corp installs a card in the root of a server, you may trash the top card of your stack to draw 1 card.",
  "title": "Lago Parano√° Shelter"
}

=== mpwcode/netrunner/v2/cards/strike_fund.json
{
  "id": "strike_fund",
  "card_type_id": "event",
  "cost": 1,
  "deck_limit": 3,
  "faction_id": "anarch",
  "influence_cost": 1,
  "is_unique": false,
  "side_id": "runner",
  "stripped_text": "Gain 4 credits. When this event is trashed from your grip or stack, you may gain 2 credits.",
  "stripped_title": "Strike Fund",
  "text": "Gain 4[credit].\nWhen this event is trashed from your grip or stack, you may gain 2[credit].",
  "title": "Strike Fund"
}

=== mpwcode/netrunner/v2/cards/sneakdoor_prime.json
{
  "card_type_id": "program",
  "cost": 6,
  "deck_limit": 3,
  "faction_id": "neutral_runner",
  "id": "sneakdoor_prime",
  "influence_cost": 0,
  "is_unique": false,
  "memory_cost": 2,
  "side_id": "runner",
  "stripped_text": "click,click: Make a run on a remote server. If successful, instead treat it as a successful run on a central server.",
  "stripped_title": "Sneakdoor Prime",
  "text": "[click],[click]: Make a run on a remote server. If successful, instead treat it as a successful run on a central server.",
  "title": "Sneakdoor Prime",
  "layout_id": "copy",
  "faces": [
    {
      "stripped_text": "click,click: Make a run on a central server. If successful, instead treat it as a successful run on a remote server.",
      "text": "[click],[click]: Make a run on a central server. If successful, instead treat it as a successful run on a remote server."
    }
  ]
}

=== mpwcode/netrunner/v2/cards/mercury_chrome_libertador.json
{
  "id": "mercury_chrome_libertador",
  "base_link": 0,
  "card_type_id": "runner_identity",
  "deck_limit": 1,
  "faction_id": "criminal",
  "influence_limit": 15,
  "is_unique": false,
  "minimum_deck_size": 45,
  "side_id": "runner",
  "stripped_text": "Whenever you breach HQ or R&D during a run, if you did not break any subroutines during that run, you may access 1 additional card. Use this ability only once per turn.",
  "stripped_title": "Mercury: Chrome Libertador",
  "subtypes": ["bioroid"],
  "text": "Whenever you breach HQ or R&D during a run, if you did not break any subroutines during that run, you may access 1 additional card. Use this ability only once per turn.",
  "title": "Mercury: Chrome Libertador"
}
