=== mpwcode/netrunner/schema/v2/cards_schema.json
{
  "$id": "https://github.com/netrunnerdb/netrunner-cards-json/blob/master/schema/v2/cards_schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "allOf": [
    {
      "title": "Faction id must be valid for the side.",
      "type": "object",
      "oneOf": [
        {
          "properties": {
            "side_id": {
              "const": "corp"
            },
            "faction_id": {
              "enum": [
                "haas_bioroid",
                "jinteki",
                "nbn",
                "neutral_corp",
                "weyland_consortium"
              ]
            }
          }
        },
        {
          "properties": {
            "side_id": {
              "const": "runner"
            },
            "faction_id": {
              "enum": [
                "adam",
                "anarch",
                "apex",
                "criminal",
                "neutral_runner",
                "shaper",
                "sunny_lebeau"
              ]
            }
          }
        }
      ]
    },
    {
      "title": "Type ids must be valid for the side.",
      "type": "object",
      "oneOf": [
        {
          "properties": {
            "side_id": {
              "const": "corp"
            },
            "card_type_id": {
              "enum": [
                "agenda",
                "asset",
                "corp_identity",
                "ice",
                "operation",
                "upgrade"
              ]
            }
          }
        },
        {
          "properties": {
            "side_id": {
              "const": "runner"
            },
            "card_type_id": {
              "enum": [
                "event",
                "hardware",
                "program",
                "resource",
                "runner_identity"
              ]
            }
          }
        }
      ]
    }
  ],
  "oneOf": [
    {
      "properties": {
        "advancement_requirement": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "agenda_points": {
          "minimum": 0,
          "type": "integer"
        },
        "card_type_id": {
          "const": "agenda"
        }
      },
      "required": ["advancement_requirement", "agenda_points"]
    },
    {
      "properties": {
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "trash_cost": {
          "minimum": 0,
          "type": "integer"
        },
        "card_type_id": {
          "enum": ["asset", "upgrade"]
        }
      },
      "required": ["cost", "trash_cost"]
    },
    {
      "properties": {
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "strength": {
          "oneOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "card_type_id": {
          "enum": ["ice"]
        }
      },
      "required": ["cost", "strength"]
    },
    {
      "properties": {
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "card_type_id": {
          "enum": ["event", "hardware", "operation", "program", "resource"]
        }
      },
      "required": ["cost"]
    },
    {
      "properties": {
        "influence_limit": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "minimum_deck_size": {
          "minimum": 0,
          "type": "integer"
        },
        "card_type_id": {
          "enum": ["corp_identity", "runner_identity"]
        }
      },
      "required": ["influence_limit", "minimum_deck_size"]
    }
  ],
  "properties": {
    "advancement_requirement": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "agenda_points": {
      "minimum": 0,
      "type": "integer"
    },
    "attribution": {
      "minLength": 1,
      "type": "string"
    },
    "base_link": {
      "minimum": 0,
      "type": "integer"
    },
    "id": {
      "minLength": 1,
      "type": "string"
    },
    "cost": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "deck_limit": {
      "minimum": 1,
      "type": "integer"
    },
    "faction_id": {
      "minLength": 1,
      "type": "string"
    },
    "influence_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "influence_limit": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "layout_id": {
      "oneOf": [
        {
          "type": "string",
          "enum": ["normal", "flip", "copy", "facade", "progression"]
        },
        {
          "type": "null"
        }
      ]
    },
    "memory_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "minimum_deck_size": {
      "minimum": 0,
      "type": "integer"
    },
    "side_id": {
      "minLength": 1,
      "type": "string",
      "enum": ["corp", "runner"]
    },
    "faces": {
      "oneOf": [
        {
          "type": "array"
        },
        {
          "type": "null"
        }
      ]
    },
    "strength": {
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "stripped_text": {
      "minLength": 1,
      "type": "string"
    },
    "stripped_title": {
      "minLength": 1,
      "type": "string"
    },
    "text": {
      "minLength": 1,
      "type": "string"
    },
    "title": {
      "minLength": 1,
      "type": "string"
    },
    "trash_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "card_type_id": {
      "minLength": 1,
      "type": "string"
    },
    "is_unique": {
      "type": "boolean"
    },
    "subtypes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "id",
    "faction_id",
    "deck_limit",
    "side_id",
    "title",
    "card_type_id",
    "is_unique"
  ],
  "dependentSchemas": {
    "layout_id": {
      "oneOf": [
        {
          "properties": {
            "layout_id": {
              "oneOf": [
                {
                  "const": "normal"
                },
                {
                  "type": "null"
                }
              ]
            },
            "faces": {
              "type": "null"
            }
          }
        },
        {
          "properties": {
            "layout_id": {
              "const": "flip"
            },
            "faces": {
              "type": "array",
              "minItems": 1,
              "maxItems": 1,
              "items": {
                "type": "object"
              }
            }
          },
          "required": ["faces"]
        },
        {
          "properties": {
            "layout_id": {
              "const": "copy"
            },
            "faces": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "object"
              }
            }
          },
          "required": ["faces"]
        },
        {
          "properties": {
            "layout_id": {
              "const": "facade"
            },
            "faces": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "object"
              }
            }
          },
          "required": ["faces"]
        },
        {
          "properties": {
            "layout_id": {
              "const": "progression"
            },
            "faces": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "object"
              }
            }
          },
          "required": ["faces"]
        }
      ]
    }
  }
}

=== mpwcode/netrunner/v2/cards/evidence_collection.json
{
  "advancement_requirement": 3,
  "agenda_points": 2,
  "card_type_id": "agenda",
  "deck_limit": 3,
  "faction_id": "neutral_corp",
  "id": "evidence_collection",
  "influence_cost": 0,
  "is_unique": false,
  "side_id": "corp",
  "stripped_text": "When you win a game with Evidence Collection in your score area, reveal set 2.",
  "stripped_title": "Evidence Collection",
  "subtypes": ["research"],
  "text": "When you win a game with Evidence Collection in your score area, reveal set 2.",
  "title": "Evidence Collection",
  "layout_id": "progression",
  "faces": [
    {
      "stripped_text": "When you win a game with Evidence Collection in your score area, reveal set 5.",
      "text": "When you win a game with Evidence Collection in your score area, reveal set 5."
    },
    {
      "stripped_text": "When you win a game with Evidence Collection in your score area, reveal set 8.",
      "text": "When you win a game with Evidence Collection in your score area, reveal set 8."
    },
    {
      "stripped_text": "Evidence Collection is worth 1 fewer agenda point while in the Runner's score area.",
      "text": "Evidence Collection is worth 1 fewer agenda point while in the Runner's score area."
    }
  ]
}

=== mpwcode/netrunner/v2/cards/federal_fundraising.json
{
  "id": "federal_fundraising",
  "card_type_id": "asset",
  "cost": 0,
  "deck_limit": 3,
  "faction_id": "nbn",
  "influence_cost": 2,
  "is_unique": false,
  "side_id": "corp",
  "stripped_text": "When your turn begins, you may look at the top 3 cards of R&D and arrange them in any order. Then, if this server is not protected by ice, you may draw 1 card.",
  "stripped_title": "Federal Fundraising",
  "subtypes": ["political", "ritzy"],
  "text": "When your turn begins, you may look at the top 3 cards of R&D and arrange them in any order. Then, if this server is not protected by ice, you may draw 1 card.",
  "title": "Federal Fundraising",
  "trash_cost": 2
}

=== mpwcode/netrunner/v2/cards/lilypad.json
{
  "id": "lilypad",
  "card_type_id": "hardware",
  "cost": 4,
  "deck_limit": 3,
  "faction_id": "shaper",
  "influence_cost": 3,
  "is_unique": true,
  "side_id": "runner",
  "stripped_text": "+2 mu The first time each turn you install a program, you may draw 1 card. Limit 1 console per player.",
  "stripped_title": "LilyPAD",
  "subtypes": ["console"],
  "text": "+2[mu]\nThe first time each turn you install a program, you may draw 1 card.\nLimit 1 <strong>console</strong> per player.",
  "title": "LilyPAD"
}

=== mpwcode/netrunner/v2/cards/b_1001.json
{
  "id": "b_1001",
  "card_type_id": "asset",
  "cost": 1,
  "deck_limit": 3,
  "faction_id": "neutral_corp",
  "influence_cost": 0,
  "is_unique": true,
  "side_id": "corp",
  "stripped_text": "Remove 1 tag: End the run. You cannot use this ability during a run on this server.",
  "stripped_title": "B-1001",
  "subtypes": ["bioroid", "enforcer"],
  "text": "<strong>Remove 1 tag:</strong> End the run. You cannot use this ability during a run on this server.",
  "title": "B-1001",
  "trash_cost": 3
}

=== mpwcode/netrunner/v2/cards/balanced_coverage.json
{
  "id": "balanced_coverage",
  "card_type_id": "asset",
  "cost": 1,
  "deck_limit": 3,
  "faction_id": "nbn",
  "influence_cost": 1,
  "is_unique": false,
  "side_id": "corp",
  "stripped_text": "When your turn begins, you may choose a card type to look at the top card of R&D. If that card has the chosen type, you may reveal it and gain 2 credits.",
  "stripped_title": "Balanced Coverage",
  "subtypes": ["seedy"],
  "text": "When your turn begins, you may choose a card type to look at the top card of R&D. If that card has the chosen type, you may reveal it and gain 2[credit].",
  "title": "Balanced Coverage",
  "trash_cost": 3
}

=== mpwcode/netrunner/v2/cards/investigator_inez_delgado.json
{
  "card_type_id": "resource",
  "cost": 0,
  "deck_limit": 3,
  "faction_id": "neutral_runner",
  "id": "investigator_inez_delgado",
  "influence_cost": 0,
  "is_unique": true,
  "side_id": "runner",
  "stripped_text": "When you win a game with Investigator Inez Delgado in your score area, reveal set 2. Add Investigator Inez Delgado to your score area as an agenda worth 0 agenda points: Expose all cards in a remote server. Use this only if you have stolean an agenda this turn.",
  "stripped_title": "Investigator Inez Delgado",
  "subtypes": ["connection"],
  "text": "When you win a game with Investigator Inez Delgado in your score area, reveal set 2.\n<strong>Add Investigator Inez Delgado to your score area as an agenda worth 0 agenda points:</strong> Expose all cards in a remote server. Use this only if you have stolean an agenda this turn.",
  "title": "Investigator Inez Delgado",
  "layout_id": "progression",
  "faces": [
    {
      "stripped_text": "When you win a game with Investigator Inez Delgado in your score area, reveal set 5. Add Investigator Inez Delgado to your score area as an agenda worth 0 agenda points: Reveal the top 3 cards in R&D. Use this only if you have stolean an agenda this turn.",
      "text": "When you win a game with Investigator Inez Delgado in your score area, reveal set 5.\n<strong>Add Investigator Inez Delgado to your score area as an agenda worth 0 agenda points:</strong> Reveal the top 3 cards in R&D. Use this only if you have stolean an agenda this turn."
    },
    {
      "stripped_text": "When you win a game with Investigator Inez Delgado in your score area, reveal set 8. Add Investigator Inez Delgado to your score area as an agenda worth 0 agenda points: Reveal each card in HQ. Use this only if you have stolean an agenda this turn.",
      "text": "When you win a game with Investigator Inez Delgado in your score area, reveal set 8.\n<strong>Add Investigator Inez Delgado to your score area as an agenda worth 0 agenda points:</strong> Reveal each card in HQ. Use this only if you have stolean an agenda this turn."
    },
    {
      "stripped_text": "Add Investigator Inez Delgado to your score area as an agenda worth 0 agenda points: Reveal each card in HQ and the top card of R&D. Use this only if you have stolean an agenda this turn.",
      "text": "<strong>Add Investigator Inez Delgado to your score area as an agenda worth 0 agenda points:</strong> Reveal each card in HQ and the top card of R&D. Use this only if you have stolean an agenda this turn."
    }
  ]
}

=== mpwcode/netrunner/v2/cards/hannah_wheels_pilintra.json
{
  "id": "hannah_wheels_pilintra",
  "card_type_id": "resource",
  "cost": 2,
  "deck_limit": 3,
  "faction_id": "anarch",
  "influence_cost": 2,
  "is_unique": true,
  "side_id": "runner",
  "stripped_text": "click: Gain click. Run a remote server. When that run ends, if it was unsuccessful, take 1 tag. Use this ability only once per turn. click, trash: Gain click click. Remove 1 tag.",
  "stripped_title": "Hannah \"Wheels\" Pilintra",
  "subtypes": ["connection"],
  "text": "[click]<strong>:</strong> Gain [click]. Run a remote server. When that run ends, if it was unsuccessful, take 1 tag. Use this ability only once per turn.\n[click], [trash]<strong>:</strong> Gain [click][click]. Remove 1 tag.",
  "title": "Hannah \"Wheels\" Pilintra"
}

=== mpwcode/netrunner/v2/cards/machicolation.json
{
  "card_type_id": "ice",
  "cost": 6,
  "deck_limit": 3,
  "faction_id": "neutral_corp",
  "id": "machicolation",
  "influence_cost": 0,
  "is_unique": false,
  "side_id": "corp",
  "strength": 4,
  "stripped_text": "Subroutine Trash 1 program. Subroutine Trash 1 program. Subroutine Trash 1 piece of hardware. Subroutine The Runner loses 3 credits, if able. End the run.",
  "stripped_title": "Machicolation",
  "subtypes": ["code_gate", "destroyer"],
  "text": "[subroutine] Trash 1 program.\n[subroutine] Trash 1 program.\n[subroutine] Trash 1 piece of hardware.\n[subroutine] The Runner loses 3[credit], if able. End the run.",
  "title": "Machicolation",
  "layout_id": "copy",
  "faces": [
    {
      "stripped_text": "Subroutine Trash 1 resource. Subroutine Trash 1 resource. Subroutine Do 1 net damage. Subroutine The Runner loses click, if able. End the run.",
      "subtypes": ["code_gate", "destroyer", "ap"],
      "text": "[subroutine] Trash 1 resource.\n[subroutine] Trash 1 resource.\n[subroutine] Do 1 net damage.\n[subroutine] The Runner loses [click], if able. End the run."
    }
  ]
}
