=== mpwcode/netrunner/schema/v2/cards_schema.json
{
  "$id": "https://github.com/netrunnerdb/netrunner-cards-json/blob/master/schema/v2/cards_schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "allOf": [
    {
      "title": "Faction id must be valid for the side.",
      "type": "object",
      "oneOf": [
        {
          "properties": {
            "side_id": {
              "const": "corp"
            },
            "faction_id": {
              "enum": [
                "haas_bioroid",
                "jinteki",
                "nbn",
                "neutral_corp",
                "weyland_consortium"
              ]
            }
          }
        },
        {
          "properties": {
            "side_id": {
              "const": "runner"
            },
            "faction_id": {
              "enum": [
                "adam",
                "anarch",
                "apex",
                "criminal",
                "neutral_runner",
                "shaper",
                "sunny_lebeau"
              ]
            }
          }
        }
      ]
    },
    {
      "title": "Type ids must be valid for the side.",
      "type": "object",
      "oneOf": [
        {
          "properties": {
            "side_id": {
              "const": "corp"
            },
            "card_type_id": {
              "enum": [
                "agenda",
                "asset",
                "corp_identity",
                "ice",
                "operation",
                "upgrade"
              ]
            }
          }
        },
        {
          "properties": {
            "side_id": {
              "const": "runner"
            },
            "card_type_id": {
              "enum": [
                "event",
                "hardware",
                "program",
                "resource",
                "runner_identity"
              ]
            }
          }
        }
      ]
    }
  ],
  "oneOf": [
    {
      "properties": {
        "advancement_requirement": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "agenda_points": {
          "minimum": 0,
          "type": "integer"
        },
        "card_type_id": {
          "const": "agenda"
        }
      },
      "required": ["advancement_requirement", "agenda_points"]
    },
    {
      "properties": {
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "trash_cost": {
          "minimum": 0,
          "type": "integer"
        },
        "card_type_id": {
          "enum": ["asset", "upgrade"]
        }
      },
      "required": ["cost", "trash_cost"]
    },
    {
      "properties": {
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "strength": {
          "oneOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "card_type_id": {
          "enum": ["ice"]
        }
      },
      "required": ["cost", "strength"]
    },
    {
      "properties": {
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "card_type_id": {
          "enum": ["event", "hardware", "operation", "program", "resource"]
        }
      },
      "required": ["cost"]
    },
    {
      "properties": {
        "influence_limit": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "minimum_deck_size": {
          "minimum": 0,
          "type": "integer"
        },
        "card_type_id": {
          "enum": ["corp_identity", "runner_identity"]
        }
      },
      "required": ["influence_limit", "minimum_deck_size"]
    }
  ],
  "properties": {
    "advancement_requirement": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "agenda_points": {
      "minimum": 0,
      "type": "integer"
    },
    "attribution": {
      "minLength": 1,
      "type": "string"
    },
    "base_link": {
      "minimum": 0,
      "type": "integer"
    },
    "id": {
      "minLength": 1,
      "type": "string"
    },
    "cost": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "deck_limit": {
      "minimum": 1,
      "type": "integer"
    },
    "faction_id": {
      "minLength": 1,
      "type": "string"
    },
    "influence_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "influence_limit": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "layout_id": {
      "oneOf": [
        {
          "type": "string",
          "enum": ["normal", "flip", "copy", "facade", "progression"]
        },
        {
          "type": "null"
        }
      ]
    },
    "memory_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "minimum_deck_size": {
      "minimum": 0,
      "type": "integer"
    },
    "side_id": {
      "minLength": 1,
      "type": "string",
      "enum": ["corp", "runner"]
    },
    "faces": {
      "oneOf": [
        {
          "type": "array"
        },
        {
          "type": "null"
        }
      ]
    },
    "strength": {
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "stripped_text": {
      "minLength": 1,
      "type": "string"
    },
    "stripped_title": {
      "minLength": 1,
      "type": "string"
    },
    "text": {
      "minLength": 1,
      "type": "string"
    },
    "title": {
      "minLength": 1,
      "type": "string"
    },
    "trash_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "card_type_id": {
      "minLength": 1,
      "type": "string"
    },
    "is_unique": {
      "type": "boolean"
    },
    "subtypes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "id",
    "faction_id",
    "deck_limit",
    "side_id",
    "title",
    "card_type_id",
    "is_unique"
  ],
  "dependentSchemas": {
    "layout_id": {
      "oneOf": [
        {
          "properties": {
            "layout_id": {
              "oneOf": [
                {
                  "const": "normal"
                },
                {
                  "type": "null"
                }
              ]
            },
            "faces": {
              "type": "null"
            }
          }
        },
        {
          "properties": {
            "layout_id": {
              "const": "flip"
            },
            "faces": {
              "type": "array",
              "minItems": 1,
              "maxItems": 1,
              "items": {
                "type": "object"
              }
            }
          },
          "required": ["faces"]
        },
        {
          "properties": {
            "layout_id": {
              "const": "copy"
            },
            "faces": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "object"
              }
            }
          },
          "required": ["faces"]
        },
        {
          "properties": {
            "layout_id": {
              "const": "facade"
            },
            "faces": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "object"
              }
            }
          },
          "required": ["faces"]
        },
        {
          "properties": {
            "layout_id": {
              "const": "progression"
            },
            "faces": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "object"
              }
            }
          },
          "required": ["faces"]
        }
      ]
    }
  }
}

=== mpwcode/netrunner/v2/cards/a_teia_ip_recovery.json
{
  "id": "a_teia_ip_recovery",
  "base_link": 0,
  "card_type_id": "corp_identity",
  "deck_limit": 1,
  "faction_id": "jinteki",
  "influence_limit": 15,
  "is_unique": false,
  "minimum_deck_size": 45,
  "side_id": "corp",
  "stripped_text": "Limit 2 remote servers. The first time each turn you install a card in the root of or protecting a remote server, you may install 1 card from HQ in the root of or protecting another remote server, ignoring all costs. You cannot score the second card this turn.",
  "stripped_title": "A Teia: IP Recovery",
  "subtypes": ["division"],
  "text": "Limit 2 remote servers.\nThe first time each turn you install a card in the root of or protecting a remote server, you may install 1 card from HQ in the root of or protecting another remote server, ignoring all costs. You cannot score the second card this turn.",
  "title": "A Teia: IP Recovery"
}

=== mpwcode/netrunner/v2/cards/flip_switch.json
{
  "card_type_id": "hardware",
  "cost": 1,
  "deck_limit": 3,
  "faction_id": "criminal",
  "id": "flip_switch",
  "influence_cost": 1,
  "is_unique": false,
  "side_id": "runner",
  "stripped_text": "You cannot use this hardware during the Corp's turn. trash: Jack out. trash: Remove 1 tag. Interrupt -> trash: Reduce the base trace strength of a trace to 0.",
  "stripped_title": "Flip Switch",
  "text": "You cannot use this hardware during the Corp's turn.\n[trash]<strong>:</strong> Jack out.\n[trash]<strong>:</strong> Remove 1 tag.\n[interrupt] â†’ [trash]<strong>:</strong> Reduce the base trace strength of a trace to 0.",
  "title": "Flip Switch"
}

=== mpwcode/netrunner/v2/cards/earth_station_sea_headquarters.json
{
  "card_type_id": "corp_identity",
  "deck_limit": 1,
  "faction_id": "weyland_consortium",
  "id": "earth_station_sea_headquarters",
  "influence_limit": 15,
  "is_unique": false,
  "minimum_deck_size": 45,
  "side_id": "corp",
  "stripped_text": "Limit 1 remote server. As an additional cost to run HQ, the Runner must pay 1 credit. click: Flip this identity.",
  "stripped_title": "Earth Station: SEA Headquarters",
  "subtypes": ["division"],
  "text": "Limit 1 remote server.\nAs an additional cost to run HQ, the Runner must pay 1[credit].\n[click]<strong>:</strong> Flip this identity.",
  "title": "Earth Station: SEA Headquarters",
  "layout_id": "flip",
  "faces": [
    {
      "stripped_text": "Limit 1 remote server. As an additional cost to run a remote server, the Runner must pay 6 credits. When the Runner makes a successful run on HQ, flip this identity.",
      "stripped_title": "Earth Station: Ascending to Orbit",
      "text": "Limit 1 remote server.\nAs an additional cost to run a remote server, the Runner must pay 6[credit].\nWhen the Runner makes a successful run on HQ, flip this identity.",
      "title": "Earth Station: Ascending to Orbit"
    }
  ]
}

=== mpwcode/netrunner/v2/cards/wage_workers.json
{
  "id": "wage_workers",
  "card_type_id": "asset",
  "cost": 2,
  "deck_limit": 3,
  "faction_id": "haas_bioroid",
  "influence_cost": 2,
  "is_unique": true,
  "side_id": "corp",
  "stripped_text": "Whenever you finish taking an action, if you have taken that action exactly 3 times this turn, gain click.",
  "stripped_title": "Wage Workers",
  "subtypes": ["bioroid", "clone", "industrial"],
  "text": "Whenever you finish taking an action, if you have taken that action exactly 3 times this turn, gain [click].",
  "title": "Wage Workers",
  "trash_cost": 4
}

=== mpwcode/netrunner/v2/cards/nova_initiumia_catalyst_impetus.json
{
  "base_link": 0,
  "card_type_id": "runner_identity",
  "deck_limit": 1,
  "faction_id": "neutral_runner",
  "id": "nova_initiumia_catalyst_impetus",
  "influence_limit": null,
  "is_unique": false,
  "minimum_deck_size": 40,
  "side_id": "runner",
  "stripped_text": "Your deck cannot include more than 1 copy of any card.",
  "stripped_title": "Nova Initiumia: Catalyst & Impetus",
  "subtypes": ["digital", "natural"],
  "text": "Your deck cannot include more than 1 copy of any card.",
  "title": "Nova Initiumia: Catalyst & Impetus"
}

=== mpwcode/netrunner/v2/cards/the_price.json
{
  "id": "the_price",
  "card_type_id": "event",
  "cost": 1,
  "deck_limit": 3,
  "faction_id": "anarch",
  "influence_cost": 2,
  "is_unique": false,
  "side_id": "runner",
  "stripped_text": "Trash the top 4 cards of your stack. You may install 1 of those cards, paying 3 credits less.",
  "stripped_title": "The Price",
  "text": "Trash the top 4 cards of your stack. You may install 1 of those cards, paying 3[credit] less.",
  "title": "The Price"
}

=== mpwcode/netrunner/v2/cards/s_dobrado.json
{
  "id": "s_dobrado",
  "card_type_id": "event",
  "cost": 2,
  "deck_limit": 3,
  "faction_id": "criminal",
  "influence_cost": 3,
  "is_unique": false,
  "side_id": "runner",
  "stripped_text": "Run a central server. The first time you encounter a piece of ice during that run, bypass it. Threat 4 -> The second time you encounter a piece of ice during that run, you may spend click to bypass it. (This ability is active if any player has 4 or more agenda points.)",
  "stripped_title": "S-Dobrado",
  "subtypes": ["run"],
  "text": "Run a central server. The first time you encounter a piece of ice during that run, bypass it.\nThreat 4 â†’ The second time you encounter a piece of ice during that run, you may spend [click] to bypass it. <em>(This ability is active if any player has 4 or more agenda points.)</em>",
  "title": "S-Dobrado"
}

=== mpwcode/netrunner/v2/cards/bahia_bands.json
{
  "id": "bahia_bands",
  "card_type_id": "event",
  "cost": 2,
  "deck_limit": 3,
  "faction_id": "neutral_runner",
  "influence_cost": 1,
  "is_unique": false,
  "side_id": "runner",
  "stripped_text": "Run any server. If successful, resolve 2 of the following in any order:  Draw 2 cards.  Install 1 card from your grip, paying 1 credit less.  Remove 1 tag.  Place 4 credits on this event. You can spend hosted credits to pay trash costs for the remainder of this run.",
  "stripped_title": "Bahia Bands",
  "subtypes": ["run"],
  "text": "Run any server. If successful, resolve 2 of the following in any order:\n• Draw 2 cards.\n• Install 1 card from your grip, paying 1[credit] less.\n• Remove 1 tag.\n• Place 4[credit] on this event. You can spend hosted credits to pay trash costs for the remainder of this run.",
  "title": "Bahia Bands"
}
