=== mpwcode/netrunner/schema/v2/printings_schema.json
{
  "$id": "https://github.com/netrunnerdb/netrunner-cards-json/blob/master/schema/v2/printings_schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "card_id": {
        "minLength": 1,
        "type": "string"
      },
      "card_set_id": {
        "minLength": 1,
        "type": "string"
      },
      "copy_quantity": {
        "minimum": 1,
        "type": "integer"
      },
      "flavor": {
        "minLength": 1,
        "type": "string"
      },
      "id": {
        "minLength": 1,
        "type": "string"
      },
      "illustrator": {
        "minLength": 1,
        "type": "string"
      },
      "layout_id": {
        "oneOf": [
          {
            "type": "string",
            "enum": ["normal", "flip", "copy", "facade", "progression"]
          },
          {
            "type": "null"
          }
        ]
      },
      "position": {
        "minimum": 1,
        "type": "integer"
      },
      "quantity": {
        "minimum": 1,
        "type": "integer"
      },
      "faces": {
        "oneOf": [
          {
            "type": "array"
          },
          {
            "type": "null"
          }
        ]
      }
    },
    "required": ["card_id", "card_set_id", "id", "position", "quantity"],
    "dependentSchemas": {
      "layout_id": {
        "oneOf": [
          {
            "properties": {
              "layout_id": {
                "oneOf": [
                  {
                    "const": "normal"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "faces": {
                "type": "null"
              }
            }
          },
          {
            "properties": {
              "layout_id": {
                "const": "flip"
              },
              "faces": {
                "type": "array",
                "minItems": 1,
                "maxItems": 1,
                "items": {
                  "type": "object"
                }
              }
            },
            "required": ["faces"]
          },
          {
            "properties": {
              "layout_id": {
                "const": "copy"
              },
              "faces": {
                "type": "array",
                "minItems": 1,
                "items": {
                  "type": "object"
                }
              }
            },
            "required": ["faces"]
          },
          {
            "properties": {
              "layout_id": {
                "const": "facade"
              },
              "faces": {
                "type": "array",
                "minItems": 1,
                "items": {
                  "type": "object"
                }
              }
            },
            "required": ["faces"]
          },
          {
            "properties": {
              "layout_id": {
                "const": "progression"
              },
              "faces": {
                "type": "array",
                "minItems": 1,
                "items": {
                  "type": "object"
                }
              }
            },
            "required": ["faces"]
          }
        ]
      }
    }
  }
}

=== mpwcode/netrunner/v2/printings/terminal_directive_campaign.json
[
  {
    "card_id": "evidence_collection",
    "card_set_id": "terminal_directive_campaign",
    "id": "14000",
    "illustrator": "Dmitry Burmak",
    "position": 1,
    "quantity": 3
  },
  {
    "card_id": "investigator_inez_delgado_a",
    "card_set_id": "terminal_directive_campaign",
    "id": "14004",
    "illustrator": "PxelSlayer",
    "position": 2,
    "quantity": 3
  },
  {
    "card_id": "lt_todachine",
    "card_set_id": "terminal_directive_campaign",
    "id": "14006",
    "illustrator": "Antonio José Manzanedo",
    "position": 3,
    "quantity": 3
  },
  {
    "card_id": "trojan",
    "card_set_id": "terminal_directive_campaign",
    "id": "14008",
    "illustrator": "Ethan Patrick Harris",
    "position": 4,
    "quantity": 3
  },
  {
    "card_id": "net_watchlist",
    "card_set_id": "terminal_directive_campaign",
    "id": "14023",
    "illustrator": "Adam S. Doyle",
    "position": 5,
    "quantity": 1
  },
  {
    "card_id": "machicolation",
    "card_set_id": "terminal_directive_campaign",
    "id": "14010",
    "illustrator": "Ed Mattinian",
    "position": 6,
    "quantity": 6,
    "layout_id": "copy",
    "copy_quantity": 3,
    "faces": [
      {
        "copy_quantity": 3
      }
    ]
  },
  {
    "card_id": "corporate_oversight",
    "card_set_id": "terminal_directive_campaign",
    "id": "14012",
    "illustrator": "Matt Zeilinger",
    "position": 7,
    "quantity": 6,
    "layout_id": "copy",
    "copy_quantity": 3,
    "faces": [
      {
        "copy_quantity": 3
      }
    ]
  },
  {
    "card_id": "investigator_inez_delgado",
    "card_set_id": "terminal_directive_campaign",
    "id": "14014",
    "illustrator": "Matt Zeilinger",
    "position": 8,
    "quantity": 3
  },
  {
    "card_id": "surveillance_network_key",
    "card_set_id": "terminal_directive_campaign",
    "id": "14018",
    "illustrator": "Michał Miłkowski",
    "position": 9,
    "quantity": 3
  },
  {
    "card_id": "bmi_buffer",
    "card_set_id": "terminal_directive_campaign",
    "id": "14020",
    "illustrator": "Timur Shevtsov",
    "position": 10,
    "quantity": 3
  },
  {
    "card_id": "shadow_team",
    "card_set_id": "terminal_directive_campaign",
    "id": "14022",
    "illustrator": "Adam Schumpert",
    "position": 11,
    "quantity": 3
  },
  {
    "card_id": "security_leak",
    "card_set_id": "terminal_directive_campaign",
    "id": "14009",
    "illustrator": "Jason Juta",
    "position": 12,
    "quantity": 1
  },
  {
    "card_id": "the_masque",
    "card_set_id": "terminal_directive_campaign",
    "id": "14024",
    "illustrator": "PxelSlayer",
    "position": 13,
    "quantity": 6,
    "layout_id": "copy",
    "copy_quantity": 3,
    "faces": [
      {
        "copy_quantity": 3
      }
    ]
  },
  {
    "card_id": "sneakdoor_prime",
    "card_set_id": "terminal_directive_campaign",
    "id": "14026",
    "illustrator": "Dmitry Prosvirnin",
    "position": 14,
    "quantity": 6,
    "layout_id": "copy",
    "copy_quantity": 3,
    "faces": [
      {
        "copy_quantity": 3
      }
    ]
  }
]
